import { makeStyles, tokens } from '@fluentui/react-components'

export const useStyles = makeStyles({
  page: {
    minHeight: '100vh',
    paddingTop: '28px',
    paddingRight: '28px',
    paddingBottom: '28px',
    paddingLeft: '28px',
    backgroundColor: tokens.colorNeutralBackground2,
    backgroundImage: 'linear-gradient(135deg, rgba(0, 120, 212, .10), rgba(16, 124, 16, .07) 45%, rgba(196, 49, 75, .08))',
    color: tokens.colorNeutralForeground1,
    overflowX: 'hidden',

    '@media (max-width: 720px)': {
      paddingTop: '16px',
      paddingRight: '16px',
      paddingBottom: '16px',
      paddingLeft: '16px',
    },
  },
  shell: {
    width: '100%',
    maxWidth: '1120px',
    marginRight: 'auto',
    marginLeft: 'auto',
    display: 'grid',
    gap: '16px',
    alignContent: 'start',
  },
  playbackGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 320px',
    alignItems: 'start',
    gap: '16px',

    '@media (max-width: 920px)': {
      gridTemplateColumns: '1fr',
    },
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '8px',
    flexWrap: 'wrap',
  },
  titleBlock: {
    minWidth: 0,
    display: 'grid',
    gap: '6px',
  },
  title: {
    overflowWrap: 'anywhere',
  },
  meta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  surface: {
    display: 'grid',
    gap: '16px',
    paddingTop: '16px',
    paddingRight: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackgroundAlpha,
    backdropFilter: 'blur(16px)',
    boxShadow: tokens.shadow8,
  },
  media: {
    width: '100%',
    borderRadius: '8px',
    backgroundColor: '#000',
  },
  video: {
    display: 'block',
    maxHeight: 'calc(100vh - 190px)',
  },
  audio: {
    minHeight: '56px',
  },
  hiddenMedia: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    opacity: 0,
    pointerEvents: 'none',
  },
  audioDisplay: {
    minHeight: '220px',
    display: 'grid',
    placeItems: 'center',
    gap: '8px',
    paddingTop: '24px',
    paddingRight: '24px',
    paddingBottom: '24px',
    paddingLeft: '24px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    textAlign: 'center',
    overflowWrap: 'anywhere',
  },
  playerStack: {
    position: 'relative',
    display: 'grid',
    gap: '14px',
  },
  playerControls: {
    display: 'grid',
    gap: '10px',
    paddingTop: '12px',
    paddingRight: '12px',
    paddingBottom: '12px',
    paddingLeft: '12px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
  },
  scrubberRow: {
    display: 'grid',
    gridTemplateColumns: '48px minmax(0, 1fr) 48px',
    gap: '10px',
    alignItems: 'center',
  },
  progressSlider: {
    minWidth: 0,
  },
  timeLabel: {
    color: tokens.colorNeutralForeground2,
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'center',
  },
  controlBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
  },
  controlGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  volumeGroup: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(90px, 140px) auto',
    alignItems: 'center',
    gap: '8px',

    '@media (max-width: 520px)': {
      gridTemplateColumns: 'auto minmax(0, 1fr) auto',
      width: '100%',
    },
  },
  volumeSlider: {
    minWidth: 0,
  },
  transportBar: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    gap: '12px',
    alignItems: 'center',
    paddingTop: '10px',
    paddingRight: '12px',
    paddingBottom: '10px',
    paddingLeft: '12px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
  },
  transportInfo: {
    minWidth: 0,
    display: 'grid',
    justifyItems: 'center',
    textAlign: 'center',
  },
  status: {
    minHeight: '260px',
    display: 'grid',
    placeItems: 'center',
    textAlign: 'center',
  },
  statusContent: {
    display: 'grid',
    gap: '10px',
    justifyItems: 'center',
  },
  emptyIcon: {
    fontSize: '42px',
    color: tokens.colorBrandForeground1,
  },
  dialogContent: {
    display: 'grid',
    gap: '12px',
    minWidth: 'min(560px, calc(100vw - 72px))',
  },
  librarySurface: {
    maxWidth: 'min(980px, calc(100vw - 48px))',
  },
  rootSelector: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  folderToolbar: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    gap: '10px',
    alignItems: 'center',
  },
  pathLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: tokens.colorNeutralForeground2,
  },
  folderLoading: {
    minHeight: '220px',
    display: 'grid',
    placeItems: 'center',
  },
  entryList: {
    maxHeight: '360px',
    overflowY: 'auto',
    display: 'grid',
    gap: '6px',
    alignContent: 'start',
  },
  entryRow: {
    width: '100%',
    minHeight: '42px',
    display: 'grid',
    gridTemplateColumns: '28px minmax(0, 1fr)',
    alignItems: 'center',
    gap: '10px',
    paddingTop: '8px',
    paddingRight: '10px',
    paddingBottom: '8px',
    paddingLeft: '10px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    cursor: 'pointer',
    font: 'inherit',
    textAlign: 'left',

    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  entryIcon: {
    display: 'grid',
    placeItems: 'center',
    color: tokens.colorBrandForeground1,
    fontSize: '20px',
  },
  playlistPanel: {
    display: 'grid',
    gap: '12px',
    paddingTop: '14px',
    paddingRight: '14px',
    paddingBottom: '14px',
    paddingLeft: '14px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackgroundAlpha,
    backdropFilter: 'blur(16px)',
    boxShadow: tokens.shadow8,
  },
  playlistHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'flex-start',
  },
  trackList: {
    maxHeight: 'min(520px, calc(100vh - 230px))',
    overflowY: 'auto',
    display: 'grid',
    gap: '6px',
  },
  trackButton: {
    width: '100%',
    minHeight: '54px',
    justifyContent: 'start',
  },
  trackInfo: {
    minWidth: 0,
    display: 'grid',
    justifyItems: 'start',
    textAlign: 'left',
  },
  trackName: {
    maxWidth: '220px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  trackPath: {
    maxWidth: '220px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  panelFallback: {
    minHeight: '120px',
    display: 'grid',
    placeItems: 'center',
  },
  libraryCreate: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: '10px',
    alignItems: 'end',

    '@media (max-width: 640px)': {
      gridTemplateColumns: '1fr',
    },
  },
  libraryList: {
    maxHeight: '360px',
    overflowY: 'auto',
    display: 'grid',
    gap: '8px',
  },
  libraryRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: '12px',
    alignItems: 'center',
    paddingTop: '12px',
    paddingRight: '12px',
    paddingBottom: '12px',
    paddingLeft: '12px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,

    '@media (max-width: 640px)': {
      gridTemplateColumns: '1fr',
    },
  },
  libraryInfo: {
    minWidth: 0,
    display: 'grid',
    gap: '6px',
  },
  libraryActions: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',

    '@media (max-width: 640px)': {
      justifyContent: 'flex-start',
    },
  },
  libraryEditorGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: '14px',

    '@media (max-width: 820px)': {
      gridTemplateColumns: '1fr',
    },
  },
  libraryColumn: {
    minWidth: 0,
    display: 'grid',
    gap: '10px',
    alignContent: 'start',
  },
  selectableRow: {
    minHeight: '42px',
    display: 'grid',
    gridTemplateColumns: 'auto 28px minmax(0, 1fr)',
    alignItems: 'center',
    gap: '8px',
    paddingTop: '8px',
    paddingRight: '10px',
    paddingBottom: '8px',
    paddingLeft: '10px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
  },
  libraryDraftList: {
    maxHeight: '420px',
    overflowY: 'auto',
    display: 'grid',
    gap: '6px',
    alignContent: 'start',
  },
  draftRow: {
    display: 'grid',
    gridTemplateColumns: '28px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '8px',
    paddingTop: '8px',
    paddingRight: '8px',
    paddingBottom: '8px',
    paddingLeft: '8px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    cursor: 'grab',

    ':active': {
      cursor: 'grabbing',
    },
  },
  draftRowDragging: {
    opacity: 0.72,
    backgroundColor: tokens.colorNeutralBackground1Hover,
    borderTopColor: tokens.colorBrandStroke1,
    borderRightColor: tokens.colorBrandStroke1,
    borderBottomColor: tokens.colorBrandStroke1,
    borderLeftColor: tokens.colorBrandStroke1,
  },
  draftActions: {
    display: 'flex',
    gap: '4px',
  },
})
