import { makeStyles, tokens } from '@fluentui/react-components'

export const useStyles = makeStyles({
  page: {
    position: 'relative',
    minHeight: '100vh',
    paddingTop: '28px',
    paddingRight: '28px',
    paddingBottom: '28px',
    paddingLeft: '28px',
    backgroundColor: tokens.colorNeutralBackground2,
    backgroundImage: 'linear-gradient(135deg, rgba(0, 120, 212, .08), rgba(16, 124, 16, .06) 52%, rgba(250, 174, 64, .08))',
    color: tokens.colorNeutralForeground1,

    '@media (max-width: 720px)': {
      paddingTop: '18px',
      paddingRight: '16px',
      paddingBottom: '18px',
      paddingLeft: '16px',
    },
  },
  shell: {
    width: '100%',
    maxWidth: '1120px',
    marginRight: 'auto',
    marginLeft: 'auto',
    display: 'grid',
    gap: '18px',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    flexWrap: 'wrap',
  },
  titleBlock: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  titleIcon: {
    width: '48px',
    height: '48px',
    display: 'grid',
    placeItems: 'center',
    borderRadius: '8px',
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: '26px',
    flexShrink: 0,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  roots: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  toolbar: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: '12px',
    alignItems: 'center',

    '@media (max-width: 720px)': {
      gridTemplateColumns: '1fr',
    },
  },
  breadcrumbs: {
    minHeight: '36px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  },
  crumbButton: {
    minWidth: '0',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '8px',
    flexWrap: 'wrap',

    '@media (max-width: 720px)': {
      justifyContent: 'flex-start',
    },
  },
  list: {
    display: 'grid',
    gap: '8px',
  },
  row: {
    minHeight: '64px',
    display: 'grid',
    gridTemplateColumns: '36px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '12px',
    paddingTop: '10px',
    paddingRight: '12px',
    paddingBottom: '10px',
    paddingLeft: '12px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  interactiveRow: {
    cursor: 'pointer',

    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  rowIcon: {
    width: '36px',
    height: '36px',
    display: 'grid',
    placeItems: 'center',
    borderRadius: '8px',
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
    fontSize: '22px',
  },
  rowInfo: {
    minWidth: 0,
    display: 'grid',
    gap: '4px',
  },
  truncate: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: tokens.colorNeutralForeground2,
    flexWrap: 'wrap',
  },
  rowActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '6px',
  },
  deleteAction: {
    color: tokens.colorStatusDangerForeground1,

    ':hover': {
      color: tokens.colorStatusDangerForeground1,
    },
    ':active': {
      color: tokens.colorStatusDangerForeground1,
    },
  },
  center: {
    minHeight: '280px',
    display: 'grid',
    placeItems: 'center',
  },
  emptyState: {
    minHeight: '260px',
    display: 'grid',
    placeItems: 'center',
    textAlign: 'center',
    color: tokens.colorNeutralForeground2,
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'dashed',
    borderRightStyle: 'dashed',
    borderBottomStyle: 'dashed',
    borderLeftStyle: 'dashed',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackgroundAlpha,
  },
  dialogForm: {
    display: 'grid',
    gap: '14px',
    minWidth: '320px',

    '@media (max-width: 480px)': {
      minWidth: '0',
    },
  },
  hiddenInput: {
    display: 'none',
  },
  dropOverlay: {
    position: 'fixed',
    top: '0',
    right: '0',
    bottom: '0',
    left: '0',
    zIndex: 10,
    display: 'grid',
    placeItems: 'center',
    paddingTop: '28px',
    paddingRight: '28px',
    paddingBottom: '28px',
    paddingLeft: '28px',
    pointerEvents: 'none',
    backgroundColor: 'rgba(0, 0, 0, .28)',
  },
  dropMessage: {
    width: 'min(420px, 100%)',
    minHeight: '160px',
    display: 'grid',
    placeItems: 'center',
    alignContent: 'center',
    gap: '6px',
    textAlign: 'center',
    borderRadius: '8px',
    borderTopWidth: '2px',
    borderRightWidth: '2px',
    borderBottomWidth: '2px',
    borderLeftWidth: '2px',
    borderTopStyle: 'dashed',
    borderRightStyle: 'dashed',
    borderBottomStyle: 'dashed',
    borderLeftStyle: 'dashed',
    borderTopColor: tokens.colorBrandStroke1,
    borderRightColor: tokens.colorBrandStroke1,
    borderBottomColor: tokens.colorBrandStroke1,
    borderLeftColor: tokens.colorBrandStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    boxShadow: tokens.shadow16,
  },
  taskList: {
    display: 'grid',
    gap: '10px',
  },
  taskPanel: {
    display: 'grid',
    gap: '10px',
    paddingTop: '12px',
    paddingRight: '14px',
    paddingBottom: '12px',
    paddingLeft: '14px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  taskHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '12px',
  },
  taskInfo: {
    minWidth: 0,
    display: 'grid',
    gap: '2px',
  },
  taskMeta: {
    color: tokens.colorNeutralForeground2,
  },
  taskActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
  },
  drawerEmpty: {
    minHeight: '180px',
    display: 'grid',
    placeItems: 'center',
    textAlign: 'center',
    color: tokens.colorNeutralForeground2,
  },
})
