/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDesktop {
    }
    interface AppLogin {
    }
    interface AppRoot {
    }
    interface AppSplashScreen {
    }
}
declare global {
    interface HTMLAppDesktopElement extends Components.AppDesktop, HTMLStencilElement {
    }
    var HTMLAppDesktopElement: {
        prototype: HTMLAppDesktopElement;
        new (): HTMLAppDesktopElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSplashScreenElement extends Components.AppSplashScreen, HTMLStencilElement {
    }
    var HTMLAppSplashScreenElement: {
        prototype: HTMLAppSplashScreenElement;
        new (): HTMLAppSplashScreenElement;
    };
    interface HTMLElementTagNameMap {
        "app-desktop": HTMLAppDesktopElement;
        "app-login": HTMLAppLoginElement;
        "app-root": HTMLAppRootElement;
        "app-splash-screen": HTMLAppSplashScreenElement;
    }
}
declare namespace LocalJSX {
    interface AppDesktop {
    }
    interface AppLogin {
    }
    interface AppRoot {
    }
    interface AppSplashScreen {
    }
    interface IntrinsicElements {
        "app-desktop": AppDesktop;
        "app-login": AppLogin;
        "app-root": AppRoot;
        "app-splash-screen": AppSplashScreen;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-desktop": LocalJSX.AppDesktop & JSXBase.HTMLAttributes<HTMLAppDesktopElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-splash-screen": LocalJSX.AppSplashScreen & JSXBase.HTMLAttributes<HTMLAppSplashScreenElement>;
        }
    }
}
