import { makeStyles, tokens } from '@fluentui/react-components'

export const useStyles = makeStyles({
  page: {
    minHeight: '100vh',
    paddingTop: '28px',
    paddingRight: '28px',
    paddingBottom: '28px',
    paddingLeft: '28px',
    backgroundColor: tokens.colorNeutralBackground2,
    backgroundImage: 'linear-gradient(135deg, rgba(0, 120, 212, .08), rgba(16, 124, 16, .06) 50%, rgba(250, 174, 64, .08))',
    color: tokens.colorNeutralForeground1,

    '@media (max-width: 720px)': {
      paddingTop: '18px',
      paddingRight: '16px',
      paddingBottom: '18px',
      paddingLeft: '16px',
    },
  },
  shell: {
    width: '100%',
    maxWidth: '1180px',
    marginRight: 'auto',
    marginLeft: 'auto',
    display: 'grid',
    gap: '20px',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    flexWrap: 'wrap',
  },
  titleBlock: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  titleIcon: {
    width: '48px',
    height: '48px',
    display: 'grid',
    placeItems: 'center',
    borderRadius: '8px',
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: '26px',
    flexShrink: 0,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  stats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '12px',

    '@media (max-width: 720px)': {
      gridTemplateColumns: '1fr',
    },
  },
  statPanel: {
    minHeight: '86px',
    paddingTop: '14px',
    paddingRight: '16px',
    paddingBottom: '14px',
    paddingLeft: '16px',
    display: 'grid',
    alignContent: 'center',
    gap: '4px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  statValue: {
    fontSize: '26px',
    lineHeight: '32px',
    fontWeight: tokens.fontWeightSemibold,
  },
  toolbar: {
    display: 'grid',
    gridTemplateColumns: 'minmax(240px, 420px) auto',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',

    '@media (max-width: 640px)': {
      gridTemplateColumns: '1fr',
    },
  },
  search: {
    width: '100%',
  },
  hiddenInput: {
    display: 'none',
  },
  content: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 340px',
    gap: '16px',
    alignItems: 'start',

    '@media (max-width: 940px)': {
      gridTemplateColumns: '1fr',
    },
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '14px',
  },
  appCard: {
    minHeight: '210px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderRadius: '8px',
  },
  selectedCard: {
    outlineWidth: '2px',
    outlineStyle: 'solid',
    outlineColor: tokens.colorBrandStroke1,
  },
  readOnlyCard: {
    backgroundColor: tokens.colorNeutralBackground3,
  },
  appIcon: {
    width: '42px',
    height: '42px',
    display: 'grid',
    placeItems: 'center',
    borderRadius: '8px',
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
    fontSize: '24px',
  },
  cardBody: {
    display: 'grid',
    gap: '12px',
  },
  description: {
    minHeight: '44px',
    color: tokens.colorNeutralForeground2,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflowY: 'hidden',
  },
  badges: {
    minHeight: '26px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  },
  details: {
    position: 'sticky',
    top: '20px',
    display: 'grid',
    gap: '16px',
    paddingTop: '16px',
    paddingRight: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground1,

    '@media (max-width: 940px)': {
      display: 'none',
    },
  },
  drawer: {
    width: 'min(88vw, 380px)',
  },
  drawerBody: {
    display: 'grid',
    alignContent: 'start',
    gap: '16px',
  },
  detailsHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
  },
  detailRows: {
    display: 'grid',
    gap: '12px',
  },
  detailRow: {
    display: 'grid',
    gap: '4px',
  },
  monospace: {
    fontFamily: tokens.fontFamilyMonospace,
    overflowWrap: 'anywhere',
  },
  permissionsList: {
    display: 'grid',
    gap: '8px',
  },
  sourceGroup: {
    display: 'grid',
    gap: '8px',
  },
  sourceGroupHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
  },
  permissionsHeader: {
    minHeight: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
  },
  permissionsTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  iconButton: {
    width: '32px',
    height: '32px',
    minWidth: '32px',
  },
  permissionItem: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    alignItems: 'flex-start',
    gap: '10px',
    paddingTop: '10px',
    paddingRight: '10px',
    paddingBottom: '10px',
    paddingLeft: '10px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
  },
  permissionInfo: {
    minWidth: 0,
    display: 'grid',
    gap: '2px',
  },
  permissionDescription: {
    color: tokens.colorNeutralForeground2,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  updatePanel: {
    display: 'grid',
    gap: '8px',
    alignItems: 'start',
  },
  updateProgress: {
    display: 'grid',
    gap: '8px',
    paddingTop: '10px',
    paddingRight: '10px',
    paddingBottom: '10px',
    paddingLeft: '10px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
  },
  updateProgressHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '8px',
  },
  truncate: {
    minWidth: 0,
    overflowX: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  center: {
    minHeight: '280px',
    display: 'grid',
    placeItems: 'center',
  },
  emptyState: {
    minHeight: '260px',
    display: 'grid',
    placeItems: 'center',
    textAlign: 'center',
    color: tokens.colorNeutralForeground2,
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderRightWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderTopStyle: 'dashed',
    borderRightStyle: 'dashed',
    borderBottomStyle: 'dashed',
    borderLeftStyle: 'dashed',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackgroundAlpha,
  },
  emptyHeader: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: '6px',
  },
})
