CREATE TABLE if NOT EXISTS users_to_apps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid REFERENCES users (uuid) ON DELETE CASCADE ON UPDATE CASCADE,
    package_name REFERENCES apps (package_name) ON DELETE CASCADE ON UPDATE CASCADE
);